global:
  resolve_timeout: 5m

route:
  receiver: 'devnull'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h

# Optional routes to Slack/Email (uncomment after setting env vars and enabling receivers below)
#  routes:
#    - matchers: [ severity = "critical" ]
#      receiver: 'slack'
#    - matchers: [ severity = "warning" ]
#      receiver: 'email'

# Receivers
receivers:
  - name: 'devnull'
    webhook_configs: []

  # Slack receiver (uncomment after setting $ALERT_SLACK_WEBHOOK_URL)
  # - name: 'slack'
  #   slack_configs:
  #     - send_resolved: true
  #       api_url: ${ALERT_SLACK_WEBHOOK_URL}
  #       channel: ${ALERT_SLACK_CHANNEL}
  #       title: "[FADO CRM] {{ .Status | toUpper }}: {{ .CommonAnnotations.summary }}"
  #       text: >-
  #         {{ range .Alerts }}*{{ .Labels.alertname }}* ({{ .Labels.severity }})\n{{ .Annotations.description }}\n{{ end }}

  # Email receiver (uncomment after setting SMTP vars)
  # - name: 'email'
  #   email_configs:
  #     - send_resolved: true
  #       to: ${ALERT_EMAIL_TO}
  #       from: ${ALERT_EMAIL_FROM}
  #       smarthost: ${ALERT_SMTP_HOST}:${ALERT_SMTP_PORT}
  #       auth_username: ${ALERT_SMTP_USER}
  #       auth_password: ${ALERT_SMTP_PASSWORD}
  #       require_tls: true
