name: typecheck

on:
  push:
    branches: [ main, omnara-claude-20250923000733, feat/** ]
  pull_request:
    branches: [ "**" ]

jobs:
  mypy:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install mypy
        run: |
          python -m pip install --upgrade pip
          pip install mypy types-requests

      - name: Run mypy (non-blocking)
        run: |
          mypy --python-version 3.12 --ignore-missing-imports fado_crm/backend || true
